---

## Init

- name: Ensure project directory exists
  ansible.builtin.file:
    path: "{{ docker_project_path }}"
    state: directory
    mode: '0755'
  tags: ["init"]

## Configure

- name: Copy configuration files
  ansible.builtin.copy:
    src: "./"
    dest: "{{ docker_project_path }}/"
    directory_mode : '0755'
    mode:            '0644'

- name: Template requirements.txt
  ansible.builtin.template:
    src: requirements.txt.j2
    dest: "{{ docker_project_path }}/requirements.txt"
    mode: '0644'

- name: Init .env
  ansible.builtin.copy:
    remote_src: true
    src:  "{{ docker_project_path }}/.env.example"
    dest: "{{ docker_project_path }}/.env"
    mode: '0644'

- name: Register json env variables
  ansible.builtin.set_fact:
    semaphore_env_vars_json: "{{ semaphore_env_vars | default({}) | to_json }}"
    semaphore_forwarded_env_vars_json: "{{ semaphore_forwarded_env_vars | default([]) | to_json }}"

- name: Configure .env
  ansible.builtin.lineinfile:
    path: "{{ docker_project_path }}/.env"
    regexp: '^#?\s*{{ item.option }}\s*=.*$'
    line: "{{ item.option }}={{ vars[item.var] }}"
  no_log: "{{ item.option == 'SEMAPHORE_DB_PASS'
           or item.option == 'SEMAPHORE_ADMIN_PASSWORD'
           or item.option == 'SEMAPHORE_COOKIE_HASH'
           or item.option == 'SEMAPHORE_COOKIE_ENCRYPTION'
           or item.option == 'SEMAPHORE_ACCESS_KEY_ENCRYPTION'
           or item.option == 'SEMAPHORE_LDAP_PASSWORD' }}"
  when: vars[item.var] is defined
  loop: "{{ semaphore_env }}"

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_project_path }}/docker-compose.yml"
    mode: '0644'
    # validate: "{{ docker_cli }} compose -f %s config" #
    backup: true

- name: Validate docker-compose.yml
  ansible.builtin.command: "{{ docker_cli }} compose -f {{ docker_project_path }}/docker-compose.yml config"
  changed_when: false

## Run

- name: Start app
  ansible.builtin.include_role: { name: djuuu.docker_project, tasks_from: compose-up }
