---

- name: Authenticate
  ansible.builtin.uri:
    url: "{{ semaphore_api_base_url }}/auth/login"
    method: POST
    body_format: json
    body:
      auth:     "{{ semaphore_admin }}"
      password: "{{ semaphore_admin_password }}"
    status_code: [204]
    validate_certs: "{{ semaphore_api_validate_certs }}"
  register: login_response

- name: Register cookie
  ansible.builtin.set_fact:
    semaphore_cookie: "{{ login_response.cookies_string }}"

- name: Generate token
  ansible.builtin.uri:
    url: "{{ semaphore_api_base_url }}/user/tokens"
    method: POST
    headers:
      Cookie: "{{ semaphore_cookie }}"
    status_code: [201]
    validate_certs: "{{ semaphore_api_validate_certs }}"
  register: token_response

- name: Register token
  ansible.builtin.set_fact:
    semaphore_token: "{{ token_response.json.id }}"
