---

- name: "Backup project {{ item.id }}"
  ansible.builtin.uri:
    url: "{{ semaphore_api_base_url }}/project/{{ item.id }}/backup"
    headers:
      Authorization: "Bearer {{ semaphore_token }}"
    validate_certs: "{{ semaphore_api_validate_certs }}"
  register: backup_response

- name: Register backup response
  ansible.builtin.set_fact:
    semaphore_project_backup: "{{ backup_response.json }}"
