---

- name: "Restore project"
  ansible.builtin.uri:
    url: "{{ semaphore_api_base_url }}/projects/restore"
    method: POST
    body_format: json
    body: "{{ backup_content }}"
    status_code: [200]
    headers:
      Authorization: "Bearer {{ semaphore_token }}"
    validate_certs: "{{ semaphore_api_validate_certs }}"
  register: restore_response

- name: Show restore response
  ansible.builtin.debug: { var: restore_response }

- name: Register restore response
  ansible.builtin.set_fact:
    semaphore_project_restore: "{{ restore_response.json }}"
